version: '3.4'
services:
  hugo:
    image: flemay/hugo
    volumes:
      - .:/opt/app
    env_file: .env
    ports:
      - "1313:1313"
    command: ./scripts/server.sh

  netlify:
    image: flemay/netlify
    volumes:
      - .:/opt/app
    env_file: .env